config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { :invitations => 'users/invitations' }

  root to: 'main#root'
  get "/whitelist" => "main#whitelist"
  get "/blacklist" => "main#blacklist"

  resource :profile
  resources :users
  resources :clients
  resources :domain_sets
  resources :host_lists

  namespace :api do
    namespace :v1 do
      resources :users do
        resources :traffics
      end
    end
  end

end

app/models/domain_set.rb
# == Schema Information
#
# Table name: domain_sets
#
#  id         :integer          not null, primary key
#  content    :text
#  title      :string
#  family     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class DomainSet < ApplicationRecord
  enumerize :family, in: [ :blocked, :local, :lag ], scope: true

  validates :title, :content, presence: true

  def domains
    (content || "").split("\n").map do |line|
      line.sub(/#.*\z/, "").strip.presence
    end.compact
  end
end

app/controllers/domain_sets_controller.rb
class DomainSetsController < ApplicationController
  load_and_authorize_resource

  def index
    @q = @domain_sets.search(params[:q])
    @domain_sets = @q.result.page(params[:page])
  end

  def new
  end

  def create
    @domain_set.save
    respond_with @domain_set, location: -> { ok_url_or_default domain_sets_path }
  end

  def edit
  end

  def update
    @domain_set.update(domain_set_params)
    respond_with @domain_set, location: -> { ok_url_or_default domain_sets_path }
  end

  def destroy
    @domain_set.destroy
    respond_with @domain_set, location: -> { ok_url_or_default domain_sets_path }
  end

protected
  def domain_set_params
    params[:domain_set].permit(:title, :content, :family) if params[:domain_set]
  end
end

app/views/domain_sets/_form.html.erb
<div class="row">
  <div class="col-md-5">
    <%= f.input :title %>
    <%= f.input :family %>
    <%= f.input :content, input_html: { rows: 15 } %>
  </div>
</div>

<div class="form-actions">
  <%= f.button :submit, class: "btn btn-primary" %>
  <%= ok_url_tag %>
  <%= cancel_link(root_url) %>
</div>

app/views/domain_sets/edit.html.erb
<h2>编辑域名集</h2>

<hr>

<%= simple_form_for @domain_set do |f| %>
  <%= render partial: "form", locals: { f: f } %>
<% end %>

app/views/domain_sets/index.html.erb
<h2>域名组列表</h2>

<hr>

<%= fume_nav @q.family_eq do |n| %>
<ul class="nav nav-tabs">
  <li class="nav-item"><%= n.content_tag nil, :a, href: domain_sets_path, class: "nav-link" do %>全部<% end %></li>

  <% DomainSet.family.options.each do |name, value| %>
    <li class="nav-item"><%= n.content_tag value, :a, href: domain_sets_path(q: { family_eq: value }), class: "nav-link" do %><%= name %><% end %></li>
  <% end %>
</ul>
<% end %>

<br>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>family</th>
      <th>Content</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @domain_sets.each do |domain_set| %>
    <tr>
      <td><%= domain_set.title %></td>
      <td><%= domain_set.family %></td>
      <td>
        <pre class="small"><%= domain_set.content %></pre>
      </td>
      <td>
        <%= link_to "编辑", edit_domain_set_path(domain_set, :ok_url => request.url) %>
        <%= link_to "删除", domain_set_path(domain_set), :method => :delete, data: { confirm: "确定删除该?" } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<nav>
  <%= paginate(@domain_sets) if !@domain_sets.empty? %>
</nav>

<div class="table-action">
  <%= link_to "添加域名组", new_domain_set_path(:ok_url => request.url), class: 'btn btn-primary' %>
</div>

app/views/domain_sets/new.html.erb
<h2>新增域名集</h2>

<hr>

<%= simple_form_for @domain_set do |f| %>
  <%= render partial: "form", locals: { f: f } %>
<% end %>