config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { :invitations => 'users/invitations' }

  root to: 'main#root'
  get "/whitelist" => "main#whitelist"
  get "/blacklist" => "main#blacklist"

  resource :profile
  resources :users
  resources :clients
  resources :domain_sets
  resources :host_lists

  namespace :api do
    namespace :v1 do
      resources :users do
        resources :traffics
      end
    end
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default("")
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  authentication_token   :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  superadmin             :boolean          default(FALSE)
#  memo                   :string(255)
#  transfer_remaining     :integer          default(0)
#  monthly_transfer       :integer          default(2147483648)
#  invitation_token       :string(255)
#  invitation_sent_at     :datetime
#  invitation_accepted_at :datetime
#  invitation_limit       :integer
#  invited_by_id          :integer
#  invited_by_type        :string(255)
#  lock_version           :integer          default(0)
#  binding_port           :integer
#  invitation_created_at  :datetime
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, # :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :traffics, dependent: :delete_all
  has_many :host_lists, dependent: :delete_all

  before_create :ensure_authentication_token
  before_create :ensure_monthly_transfer_on_create
  before_save   :ensure_binding_port

  scope :without_invitation_not_accepted, ->() { where("invitation_accepted_at IS NOT NULL OR (invitation_accepted_at IS NULL AND invitation_token IS NULL)") }
  scope :available, ->() { without_invitation_not_accepted.where('transfer_remaining > ?', 0) }

  def host_list(policy)
    host_lists.with_policy(policy).first_or_create
  end

  def ensure_monthly_transfer_on_create
    self.transfer_remaining = self.monthly_transfer if self.transfer_remaining <= 0
  end

  def ensure_authentication_token
    self.authentication_token ||= SecureRandom.hex(16)
  end

  def ensure_binding_port
    if binding_port.nil?
      begin
        port = rand(30000..50000)
      end while User.where(binding_port: port).exists?
      self.binding_port = port
    end
  end

  def password_required?
    !persisted? || !password.blank? || !password_confirmation.blank?
  end

  def transfer_using
    self.monthly_transfer - self.transfer_remaining
  end

  def recharge
    self.transfer_remaining = self.monthly_transfer if self.monthly_transfer
    self.save
  rescue ActiveRecord::StaleObjectError
    self.reload
    retry
  end

  def consume(bytes)
    self.transfer_remaining -= bytes
    self.save
  rescue ActiveRecord::StaleObjectError
    self.reload
    retry
  end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
  def index
    @users = User.available
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    binding.pry
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:notice] = 'User was successfully updated.'
      redirect_to root_url
    else
      render action: "edit"
    end
  end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  authorize_object object: :invitation, only: [ :new, :create ]

protected
  def user_params
    UserParams.new(current_ability).permit(params)
  end

  def after_invite_path_for(resource)
    users_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @q = User.search(params[:q])
    @q.sorts = 'email asc' if @q.sorts.empty?
    @users = @q.result.page(params[:page]).per(30)
  end

  def new
  end

  def show
    @now = Time.zone.now
    @recent_report = TrafficReport::Minutely.recent(@user.traffics)
    @today_report = TrafficReport::Hourly.today(@user.traffics)
    @this_month_report = TrafficReport::Daily.this_month(@user.traffics)
  end

  def create
    @user.save
    respond_with @user, location: -> { ok_url_or_default users_path }
  end

  def edit
  end

  def update
    @user.update(user_params)
    respond_with @user, location: -> { ok_url_or_default users_path }
  end

  def destroy
    @user.destroy
    respond_with @user, location: -> { ok_url_or_default users_path }
  end

protected
  def user_params
    UserParams.new(current_ability).permit(params)
  end
end

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-5">
    <% user_params = UserParams.new(current_ability) %>
    <%= f.input :email if user_params.permit_attributes.include?(:email) %>
    <%= f.input :memo if user_params.permit_attributes.include?(:memo) %>
    <%= f.input :password if user_params.permit_attributes.include?(:password) %>
    <%= f.input :password_confirmation if user_params.permit_attributes.include?(:password_confirmation) %>
    <%= f.input :transfer_remaining if user_params.permit_attributes.include?(:transfer_remaining) %>
    <%= f.input :monthly_transfer if user_params.permit_attributes.include?(:monthly_transfer) %>
  </div>
</div>

<div class="form-actions">
  <%= f.button :submit, class: "btn btn-primary" %>
  <%= ok_url_tag %>
  <%= cancel_link(root_url) %>
</div>

app/views/users/edit.html.erb
<h2>修改用户</h2>

<hr>

<%= simple_form_for @user do |f| %>
  <%= render partial: "form", locals: { f: f } %>
<% end %>

app/views/users/index.html.erb
<h2>用户列表</h2>

<hr>


<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th><%= sort_link @q, :email %></th>
      <th><%= sort_link @q, :updated_at %></th>
      <th><%= sort_link @q, :transfer_remaining %></th>
      <th><%= sort_link @q, :binding_port %></th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.email, user %><%= " (#{user.memo})" if !user.memo.blank? %></td>
      <th><%= distance_of_time_in_words_to_now(user.updated_at, include_seconds: true) + "之前" if user.updated_at %></th>
      <td><%= number_to_human_size_with_negative(user.transfer_remaining) %> / <%= number_to_human_size_with_negative(user.monthly_transfer) if user.monthly_transfer %></td>
      <td><%= user.binding_port %></td>
      <td>
        <%= link_to "编辑", edit_user_path(user, :ok_url => request.url) %>
        <%= link_to "删除", user_path(user), :method => :delete, data: { confirm: "确定删除该用户?" } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<nav>
  <%= paginate(@users) if !@users.empty? %>
</nav>

<div class="table-action">
  <%= link_to "添加用户", new_user_path(:ok_url => request.url), class: 'btn btn-primary' %>
  <%= link_to "邀请注册", new_user_invitation_path, class: 'btn btn-default' %>
</div>

app/views/users/new.html.erb
<h2>新增用户</h2>

<hr>

<%= simple_form_for @user do |f| %>
  <%= render partial: "form", locals: { f: f } %>
<% end %>

app/views/users/show.html.erb
<% content_for :head do %>
<style>
.chart {
  height: 250px;
}

.faq li {
  margin: 0.5em 0;
}
</style>
<% end %>


<div class="card mb-4">
  <div class="card-header">基础信息</div>
  <div class="card-block">
    <div class="row">
      <div class="col-md-12">
        <h4>用户帐号</h4>
        <p><%= @user.email %></p>

        <h4>
          可用流量:
          <span class="label label-primary">
            <%= number_to_human_size_with_negative(@user.transfer_remaining) %> / <%= number_to_human_size_with_negative(@user.monthly_transfer) if @user.monthly_transfer %>
          </span>
        </h4>

        <h4>HTTP 代理:</h4>
        <p>
          <% Client.available.each do |client| %>
          <code><%= Project.default_proxy_address %></code>
          <% end %>
          <%#= link_to "更换端口", user_path(user: { binding_port: nil }), method: 'put', class: "btn btn-warning-outline btn-sm", data: { confirm: '确定是否更换端口?' } %>
        </p>

        <h4>PAC 代理:</h4>
        <p>
          <label>白名单(whitelist):</label>
          <code><%= host_list_url(@user.host_list(:white), :pac) %></code>
        </p>
        <p>
          <label>黑名单(blacklist):</label>
          <code><%= host_list_url(@user.host_list(:black), :pac) %></code>
        </p>
        <p>
          <label>加速单(speedlist):</label>
          <code><%= host_list_url(@user.host_list(:speed), :pac) %></code>
        </p>
      </div>
    </div>
  </div>
</div>


<div class="card mb-4">
  <div class="card-header">最近2小时用量</div>
  <div class="card-block">
    <div id="recent-area-chart" class="chart"></div>
  </div>
</div>

<div class="card mb-4">
  <div class="card-header">当天流量</div>
  <div class="card-block">
    <div class="row">
      <div class="col-md-9">
        <div id="today-area-chart" class="chart"></div>
      </div>
      <div class="col-md-3">
        <div id="today-donut-chart" class="chart"></div>
      </div>
    </div>
  </div>
</div>

<div class="card mb-4">
  <div class="card-header">当月流量</div>
  <div class="card-block">
    <div id="this-month-bar-chart" class="chart"></div>
  </div>
</div>

<script>
// var defaultAreaOptions = {
//   hideHover: 'auto',
//   xkey: 'start_at',
//   pointSize: 0,
//   lineWidth: 1,
//   yLabelFormat: function(y) { return numberToHumanSize(y) }
// }
//
// var defaultDonutOptions = {
//   formatter: function(y, data) { return numberToHumanSize(y) }
// }

/*Morris.Area($.extend({
  element: 'today-area-chart',
  data: <%=raw JSON.pretty_generate(@today_report.chart) %>,
  goals: [ 50 * 1024 * 1024 ],
  ykeys: <%=raw @today_report.remote_ips.to_json %>,
  labels:  <%=raw @today_report.remote_ips.to_json %>,
  lineColors: <%=raw @today_report.remote_ip_colors.to_json %>,
  events: [ <%=raw @today_report.limit.start_at.to_json %> ]
}, d);

Morris.Donut($.extend({
  element: 'today-donut-chart',
  data: <%=raw @today_report.total_remote_ip_chart.to_json %>,
  colors: <%=raw @today_report.remote_ip_colors.to_json %>
}, defaultDonutOptions));

Morris.Bar({
  element: 'this-month-bar-chart',
  data: <%=raw JSON.pretty_generate(@this_month_report.chart.map { |line| line["day"] = line["start_at"].to_date; line }) %>,
  ykeys: [ "total_transfer_bytes" ],
  labels: [ "total_transfer_bytes" ],
  xkey: 'day',
  hideHover: 'auto',
  yLabelFormat: function(y) { return numberToHumanSize(y) }
});
*/
</script>