config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { :invitations => 'users/invitations' }

  root to: 'main#root'
  get "/whitelist" => "main#whitelist"
  get "/blacklist" => "main#blacklist"

  resource :profile
  resources :users
  resources :clients
  resources :domain_sets
  resources :host_lists

  namespace :api do
    namespace :v1 do
      resources :users do
        resources :traffics
      end
    end
  end

end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id             :integer          not null, primary key
#  access_token   :string(255)
#  hostname       :string(255)
#  last_access_at :datetime
#  created_at     :datetime
#  updated_at     :datetime
#  disabled       :boolean          default(FALSE)
#

class Client < ApplicationRecord

  before_validation :ensure_access_token

  validates :hostname, presence: true
  validates :access_token, presence: true, uniqueness: true

  scope :available, -> { where(disabled: false) }

  def ensure_access_token
    self.access_token = SecureRandom.hex(16) if access_token.blank?
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  load_and_authorize_resource

  def index
    @clients = @clients.page(params[:page]).per(30)
  end

  def new
  end

  def create
    @client.save
    respond_with @client, location: -> { ok_url_or_default clients_path }
  end

  def edit
  end

  def update
    @client.update(client_params)
    respond_with @client, location: -> { ok_url_or_default clients_path }
  end

  def destroy
    @client.destroy
    respond_with @client, location: -> { ok_url_or_default clients_path }
  end

protected
  def client_params
    params[:client].permit(:access_token, :hostname, :disabled) if params[:client]
  end
end

app/views/clients/_form.html.erb
<div class="row">
  <div class="col-md-5">
    <%= f.input :hostname %>
    <%= f.input :access_token %>
    <%= f.input :disabled %>
  </div>
</div>

<div class="form-actions">
	<%= f.button :submit, class: "btn btn-primary" %>
	<%= ok_url_tag %>
	<%= cancel_link(root_url) %>
</div>

app/views/clients/edit.html.erb
<h2>修改客户端</h2>

<hr>

<%= simple_form_for @client do |f| %>
  <%= render partial: "form", locals: { f: f } %>
<% end %>

app/views/clients/index.html.erb
<h2>客户端列表</h2>

<hr>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Hostname</th>
      <th>Last Access At</th>
      <th>Access Token</th>
      <th>Disabled</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each do |client| %>
    <tr>
      <td><%= client.hostname %></td>
      <th><%= distance_of_time_in_words_to_now(client.last_access_at, include_seconds: true) + "之前" if client.last_access_at %></th>
      <td><%= client.access_token %></td>
      <td><%= client.disabled %></td>
      <td>
        <%= link_to "编辑", edit_client_path(client, :ok_url => request.url) %>
        <%= link_to "删除", client_path(client), :method => :delete, data: { confirm: "确定删除该客户端?" } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<nav>
  <%= paginate(@clients) if !@clients.empty? %>
</nav>

<div class="table-action">
  <%= link_to "添加客户端", new_client_path(:ok_url => request.url), class: 'btn btn-primary' %>
</div>

app/views/clients/new.html.erb
<h2>新增客户端</h2>

<hr>

<%= simple_form_for @client do |f| %>
  <%= render partial: "form", locals: { f: f } %>
<% end %>