config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { :invitations => 'users/invitations' }

  root to: 'main#root'
  get "/whitelist" => "main#whitelist"
  get "/blacklist" => "main#blacklist"

  resource :profile
  resources :users
  resources :clients
  resources :domain_sets
  resources :host_lists

  namespace :api do
    namespace :v1 do
      resources :users do
        resources :traffics
      end
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prelude</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= javascript_pack_tag 'application', media: "all", 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>

  <%= yield :head %>
</head>
<body>

<header class="navbar navbar-toggleable-md navbar-light bg-faded mb-4">
  <div class="container mx-0 mx-sm-auto">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#bd-main-nav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <%= link_to "Prelude", root_path, class: 'navbar-brand' %>

    <div class="collapse navbar-collapse" id="bd-main-nav">
      <ul class="navbar-nav mr-auto">
        <% if can? :manage, :admin %>
          <li class="nav-item"><%= link_to "用户管理", users_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "客户端管理", clients_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "域名组管理", domain_sets_path, class: "nav-link" %></li>
        <% end %>
      </ul>

      <% if current_user %>
        <hr class="hidden-sm-up">

        <ul class="nav navbar-nav hidden-sm-up">
          <li class="nav-item"><%= link_to "修改密码", edit_user_path(current_user, ok_url: request.url), class: "nav-link" %></li>
          <li class="nav-item"><%= link_to '注销', destroy_user_session_path, method: 'delete', class: "nav-link" %></li>
        </ul>

        <ul class="navbar-nav hidden-sm-down">
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-user"></i>
              <span class="hidden-sm-down"><%= current_user.email %></span>
            </a>
            <div class="dropdown-menu">
              <%= link_to "修改密码", edit_user_path(current_user, ok_url: request.url), class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to '注销', destroy_user_session_path, method: 'delete', class: "dropdown-item" %>
            </div>
          </li>
        </ul>
      <% end %>

    </div>
  </div>
</header>


<div class="container">
  <% flash.each do |code| %>
  <div class="alert alert-success fade in">
    <a class="close" data-dismiss="alert">×</a>
    <%= flash[code[0]] %>
  </div>
  <% end %>

  <%= yield %>
</div>

</body>
</html>